### ISSUE TITLE
算法实际执行时间交流

### ISSUE THREAD

**Issue by Michael18811380328** [lf2021/Front-End-Interview#7]
> 你是指的执行用时吗？
> 我今天用两种方法的时候也是这样，但是我觉得不用纠结这个执行用时，我觉得它也会受电脑配置，网络速度的影响

你好，我这里的时间指的是实际执行时间。

在不同时间，不同设备，不同网络情况下测试，执行用时确实不同，这个值仅供参考。

从另一个角度分析：算法复杂度是样本趋近无穷大时，不同算法的效率有明显差异。LeetCode 中测试集数量有限，实际结果和理论上的算法复杂度可能不吻合。

安冰

**Comment by lf2021** [comment]
是这样，从算法复杂度层面去分析方法的利弊就好啦发自我的华为手机-------- 原始邮件 --------发件人： Michael An <notifications@github.com>日期： 2020年10月21日周三 11:30收件人： lf2021/Front-End-Interview <Front-End-Interview@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [lf2021/Front-End-Interview] 算法实际执行时间交流 (#7)

你是指的执行用时吗？
我今天用两种方法的时候也是这样，但是我觉得不用纠结这个执行用时，我觉得它也会受电脑配置，网络速度的影响

你好，我这里的时间指的是实际执行时间。
在不同时间，不同设备，不同网络情况下测试，执行用时确实不同，这个值仅供参考。
从另一个角度分析：算法复杂度是样本趋近无穷大时，不同算法的效率有明显差异。LeetCode 中测试集数量有限，实际结果和理论上的算法复杂度可能不吻合。
安冰
